
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:

  allowlist_external_dirs:
    # - /config
    # - /home
    - /config/www/grabaciones/camara_salon

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate

# Seguimiento personas
device_tracker:
      
  - platform: ping
    hosts:
      mvxp: 192.168.1.31
      mvsp: 192.168.1.30
      mvjp: 192.168.1.32
      mvep: 192.168.1.34

# Habilitando Alexa
alexa: !include alexa.yaml

# Mensajes a telegram            
telegram_bot:
 - platform: polling
   api_key: !secret telegram_bot_apy_key
   allowed_chat_ids:
     - !secret telegram_bot_chat_id
     - !secret telegram_bot_chat_id2


# Interruptor para levantar ordenador hp_javi
switch:
  - platform: wake_on_lan
    mac: !secret wol_javi_mac
    name: PCJ
    host: 192.168.1.20

sensor:
  # Sensores raspberry. #

  - platform: command_line
    name: Raspberry Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: disk_free
        arg: /
      - type: processor_use

# Sensor si alguien de la familia en casa #
  - platform: template
    sensors:
      en_casa:
        friendly_name: 'Alguien en casa'
        value_template: >-
          {%- if (is_state("person.javier","home") or is_state("person.sonia","home") or is_state("person.xavi","home"))  -%}
            true
          {%- else -%}
            false
          {%- endif -%}
        # entity_id:
        #   - person.javier
        #   - person.sonia
        #   - person.xavi

  - platform: integration
    source: sensor.consumo_potencia_casa
    name: consumo_casa
    unique_id: consumo_casa
    unit_prefix: k
    round: 2

  - platform: time_date
    display_options:
      - 'time'


# Días laborables y festivos nacionales y de Catalunya (CT)
binary_sensor:
  - platform: workday
    country: ES
    province: CT
    
  - platform: template
    sensors:
      sonia_vacaciones:
        value_template: >-
          {{ is_state_attr('calendar.sonia_vacaciones', 'message', 'Vacaciones Sonia') and state_attr('calendar.sonia_vacaciones', 'start_time') < now().strftime('%Y-%m-%d %H:%M:%S') and state_attr('calendar.sonia_vacaciones', 'end_time') > now().strftime('%Y-%m-%d %H:%M:%S') }}
      javi_vacaciones:
        value_template: >-
          {{ is_state_attr('calendar.javi_vacaciones', 'message', 'Vacaciones Javi') and state_attr('calendar.javi_vacaciones', 'start_time') < now().strftime('%Y-%m-%d %H:%M:%S') and state_attr('calendar.javi_vacaciones', 'end_time') > now().strftime('%Y-%m-%d %H:%M:%S') }}
      cole_vacaciones:
        value_template: >-
          {{ is_state_attr('calendar.cole_vacaciones', 'message', 'Vacaciones Cole') and state_attr('calendar.cole_vacaciones', 'start_time') < now().strftime('%Y-%m-%d %H:%M:%S') and state_attr('calendar.cole_vacaciones', 'end_time') > now().strftime('%Y-%m-%d %H:%M:%S') }}
      sonia_trabajo:
        value_template: >-
          {{ is_state('binary_sensor.sonia_vacaciones', 'off') and is_state('binary_sensor.workday_sensor', 'on') }}
      javier_trabajo:
        value_template: >-
          {{ is_state('binary_sensor.javi_vacaciones', 'off') and is_state('binary_sensor.workday_sensor', 'on') }}
      hay_cole:
        value_template: >-
          {{ is_state('binary_sensor.cole_vacaciones', 'off') and is_state('binary_sensor.workday_sensor', 'on') }}

  - platform: template
    sensors:
      dia_laborable:
        value_template: >-
          {{ is_state('binary_sensor.sonia_vacaciones', 'off') and is_state('binary_sensor.workday_sensor', 'on') and  is_state('binary_sensor.javi_vacaciones', 'off') and is_state('binary_sensor.workday_sensor', 'on') }}
      # dia_no_laborable:
      #   value_template: >-
      #     {{ is_state('binary_sensor.sonia_vacaciones', 'on') or is_state('binary_sensor.workday_sensor', 'off') or is_state('binary_sensor.javi_vacaciones', 'on') or is_state('binary_sensor.workday_sensor', 'off') }}

    
#Eliminando basura del historial
history:
  exclude:
    domains:
      - automation
      - updater
      - device_tracker
      - sun
      - weather
      - zone
      - scene
      - script
    entities:
      - calendar.partidos_manyanet
    entity_globs:
      - binary_sensor.mvja_*

recorder:
  purge_keep_days: 15

climate:
  # Termostatos radiadores #

  # Habitación Matrimonio
  - platform: generic_thermostat
    name: termostato_dormitorio
    unique_id: termostato_dormitorio
    heater: switch.radiador_dormitorio
    target_sensor: sensor.temperatura_dormitorio
    initial_hvac_mode: "heat"
    away_temp: 17
    target_temp: 21
    min_temp: 15
    max_temp: 23

  # Salón
  - platform: generic_thermostat
    name: termostato_salon
    unique_id: termostato_salon
    heater: switch.radiador_salon
    target_sensor: sensor.temperatura_salon
    initial_hvac_mode: "heat"
    away_temp: 17
    target_temp: 21
    min_temp: 15
    max_temp: 23

  # Habitación Xavi
  - platform: generic_thermostat
    name: termostato_xavi
    unique_id: termostato_xavi
    heater: switch.radiador_xavi
    target_sensor: sensor.temperatura_habitacion_xavi
    initial_hvac_mode: "heat"
    away_temp: 17
    target_temp: 21
    min_temp: 15
    max_temp: 23

  # Habitación Éric
  - platform: generic_thermostat
    name: termostato_eric
    unique_id: termostato_eric
    heater: switch.radiador_eric
    target_sensor: sensor.temperatura_habitacion_eric
    initial_hvac_mode: "heat"
    away_temp: 17
    target_temp: 21
    min_temp: 15
    max_temp: 23

# Gestionado los contenedores
monitor_docker:
  - name: Docker
    containers:
      - qbittorrent
      - ha
      - deconz
      - radarr
      - sonarr
      - bazarr
      - wireguard
      - amule
      - prowlarr
      - jackett
      - syncthing
      - diun
      - mqtt
    monitored_conditions:
      - version
      - state
      - status
      - containers_1cpu_percentage
      - containers_memory_percentage
      - memory_percentage
      - memory
      - cpu_percentage

# Example configuration.yaml entry
# mqtt:  
#   switch:
#     - unique_id: switchbot
#       name: "Boton AC"
#       state_topic: "homeassistant/switch/switchbot/c6:33:14:da:a5:9d/state"
#       command_topic: "homeassistant/switch/switchbot/c6:33:14:da:a5:9d/set"
#       payload_on: "ON"
#       payload_off: "OFF"
#       state_on: "ON"
#       state_off: "OFF"
#       optimistic: false
#       qos: 0
#       retain: true

# Convertir atributo potencia en sensor potencia
template:
  - sensor:
    - name: "Potencia Instantanea Servidor"
      state: "{{ state_attr('switch.localtuya_enchufe_servidor', 'current_consumption')|float(14.1) }}"
      unique_id: potencia_instantanea_servidor
      unit_of_measurement: 'W'
      device_class: power

# Registro logs.
logger:
  default: info
  logs:
  #  homeassistant.components.mqtt: debug
  #   # log level for MQTT integration
  #   homeassistant.components.nut: debug
  #     # custom_components.monitor_docker: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/24
    - 192.168.1.0/24
    - 172.18.0.0/24
